# cPanel deployment configuration
---
deployment:
    tasks:
        - export: # Export environment variables
              # REPO_PATH: "/home/username/git/repo-name"
              REPO_PATH: "/home/n1577716/public_html/goapi.qordinate.com/tes_serv_shared"
              PUBLIC_HTML: "/home/n1577716/public_html/goapi.qordinate.com/tes_serv_shared"

        - pull:
              command: "git -C $REPO_PATH pull origin main"
              description: "Pulling latest changes from the repository"

        - install-dependencies:
              command: "composer install --no-dev --optimize-autoloader --working-dir=$REPO_PATH"
              description: "Installing dependencies using Composer"

        - deploy:
              command: "rsync -avz --exclude='.git' $REPO_PATH/ $PUBLIC_HTML/"
              description: "Deploying files to public_html"

        # - finalize:
        #     command: "php $PUBLIC_HTML/artisan optimize"
        #     description: "Running optimizations for Laravel or similar frameworks"
